# Generated by Django 2.0.1 on 2019-08-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('date_aired', models.DateField(auto_now=True)),
                ('episode_file', models.FileField(default='', upload_to='episodes/')),
            ],
        ),
    ]
